language: cpp
compiler: 
- g++


before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq


install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq freeglut3-dev libxmu-dev libxi-dev cmake
 - cd ~ 
 - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3-Linux-i386.tar.gz
 - tar -xzf cmake-3.4.3-Linux-i386.tar.gz
 


before_script:
- cmake-3.4.3-Linux-i386/bin/cmake --version
- gcc --version
- g++ --version


script: 
- mkdir -p build 
- cd build 
- cmake-3.4.3-Linux-i386/bin/cmake  -DBUILD_OPENCAL_SERIAL=ON .. 
- make -j4
