language: cpp
compiler: gcc

script: mkdir -p build && cd build && cmake -DEXAMPLES:STRING=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_OPENCL:STRING=OFF -DBUILD_GL:STRING=OFF -DBUILD_OMP:STRING=OFF ..  && make 
