language: cpp
compiler: g++


before_install:
- sudo add-apt-repository  ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq


install:
 - export BASE=`pwd`
 - sudo apt-get update -qq
 - sudo apt-get install -qq freeglut3-dev libxmu-dev libxi-dev build-essential g++-4.8
 - export CXX="g++-4.8"
 - export CC="gcc-4.8"
 #cmake latest
 - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
 - tar xf cmake-3.4.3.tar.gz
 - cd cmake-3.4.3
 - ./configure
 - make 
 - sudo make install
 - export PATH=/usr/local/bin:$PATH
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
 - cd $BASE


before_script:
- cmake --version
- gcc --version
- g++ --version


script:
- mkdir -p build 
- cd build 
- cmake  -DBUILD_OPENCAL_SERIAL=ON .. 
- make
