language: cpp
compiler: gcc


before_install:
 - sudo apt-get update


install:
 - sudo apt-get install freeglut3-dev libxmu-dev libxi-dev

before_script:
- cmake --version
- gcc --version
- g++ --version


script: 
- mkdir -p build 
- cd build 
- cmake -DEXAMPLES:STRING=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_OPENCAL_CL:STRING=OFF -DBUILD_OPENCAL_GL:STRING=OFF -DBUILD_OPENCAL_OMP:STRING=OFF .. 
- make -j4
