include Makefile.inc

OPENCL_UTILS_PATH = ./OpenCL_Utils/
OPENCAL_PATH = ./OpenCAL_CL/
#SCIDDICA_PATH = ./CALCL_Sciddica/
#LIFE2D_PATH = ./CALCL_Life2D/
#LIFE3D_PATH = ./CALCL_Life3D/
#SCIARA_OPENCAL_PATH = ./CAL_Sciara
#MULTISIMULATOR_OPENCAL_PATH = ./Multisimulator
#MULTISIMULATOR_OPENCALCL_PATH = ./MultisimulatorCL
#SCIARA_OPENCALCL_PATH = ./CALCL_Sciara



all:
	cd $(OPENCL_UTILS_PATH) && $(MAKE) clean && $(MAKE)
	cd $(OPENCAL_PATH) && $(MAKE) clean && $(MAKE)
#	cd $(SCIARA_OPENCAL_PATH) && $(MAKE) clean && $(MAKE)
#	cd $(SCIARA_OPENCALCL_PATH) && $(MAKE) clean && $(MAKE)
#	cd $(MULTISIMULATOR_OPENCAL_PATH) && $(MAKE) clean && $(MAKE)
#	cd $(MULTISIMULATOR_OPENCALCL_PATH) && $(MAKE) clean  && $(MAKE)
#	cd $(SCIDDICA_PATH) && $(MAKE) clean && $(MAKE)
#	cd $(LIFE2D_PATH) && $(MAKE) clean && $(MAKE)
#	cd $(LIFE3D_PATH) && $(MAKE) clean && $(MAKE)

clean:
	cd $(OPENCL_UTILS_PATH) && $(MAKE) clean
	cd $(OPENCAL_PATH) && $(MAKE) clean
#	cd $(SCIARA_OPENCAL_PATH) && $(MAKE) clean
#	cd $(SCIARA_OPENCALCL_PATH) && $(MAKE) clean
#	cd $(MULTISIMULATOR_OPENCAL_PATH) && $(MAKE) clean
#	cd $(MULTISIMULATOR_OPENCALCL_PATH) && $(MAKE) clean
#	cd $(SCIDDICA_PATH) && $(MAKE) clean
#	cd $(LIFE2D_PATH) && $(MAKE) clean
#	cd $(LIFE3D_PATH) && $(MAKE) clean



