CC = g++
OPENCL_INC_PATH	= /usr/local/cuda/include
OPENCL_UTILS_LIB_PATH	= ../OpenCL_Utils/lib
OPENCL_UTILS_INC_PATH	= ../OpenCL_Utils/include
CFLAGS = -O0 -march=native -pipe -g -Wno-write-strings
#CFLAGS = -g -fopenmp 
#-DPROF
