#ifndef calSteeringCommon_h
#define calSteeringCommon_h

enum STEERING_OPERATION {
	STEERING_MAX = 0,
	STEERING_MIN,
	STEERING_SUM,
	STEERING_PROD,
	STEERING_LOGICAL_AND,
	STEERING_BINARY_AND,
	STEERING_LOGICAL_OR,
	STEERING_BINARY_OR,
	STEERING_LOGICAL_XOR,
	STEERING_BINARY_XOR
};

#endif
